/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Public metadata helper: DO NOT store real keys here. Read from environment instead.
export const projectId = process.env.VITE_SUPABASE_PROJECT_ID || 'REPLACE_WITH_PROJECT_ID'
export const publicAnonKey = process.env.VITE_SUPABASE_ANON_KEY || ''