name: workflow-disabled

on:
	# Only allow manual runs; pushes and PRs will not trigger anything
	workflow_dispatch:

jobs:
	noop:
		runs-on: ubuntu-latest
		steps:
			- run: echo "GitHub Actions disabled for this repo. Use Vercel auto-deploys or Vercel CLI."
